### ISSUE TITLE
Inverted player position

### ISSUE THREAD

**Issue by ThibaultLemaire** [HenriDellal/patolli#1]
Hi,

Nice little game!

Although I think the player's names are displayed the wrong way around.

![screenshot_20180827-200325](https://user-images.githubusercontent.com/21345269/44676719-625bba00-aa34-11e8-9949-e19b006f2f14.png)

I have renamed the First Player into "Me" and the Second Player into "Them". If I'm not mistaken, in one player set up, I control the green pawns and should reach the lower left corner.

**Comment by ThibaultLemaire** [comment]
The first time I played with the default set up of "Player 2" -- "Player 1" this got me confused and when I won, I thought I had actually lost and hadn't understood the game at all.

![screenshot_20180827-201147](https://user-images.githubusercontent.com/21345269/44677284-e19dbd80-aa35-11e8-8304-c32cf8b872bd.png)

Now that I have renamed the players I see there is victory condition is alright, but still the placement is strange

**Comment by HenriDellal** [comment]
Hello. I'll try to change it. Thank you for the feedback.

**Comment by BWPanda** [comment]
You control the green pieces, which start at the top-right, work their way down to the bottom-left, then back to the top-right again.

So the players names are on the correct sides (left/right) of the board, however it may be more obvious if they were displayed at the top (starting position) instead of at the bottom...
